spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false #开发的时候禁用缓存
server:
  servlet:
    context-path: /
  port: 11000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/